const types = {
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  SET_EXPENSES: 'SET_EXPENSES',
  SET_CALENDAR_DIALOG_VISIBLE: 'SET_CALENDAR_DIALOG_VISIBLE',
};

export default types;
